# action.yml
name: "Downstream Runner - Docker"
description: "Docker container to run downstream tests for pytest."
inputs:
  ACTION_IMAGE:
    description: "Docker image to use."
    require: false
    default: "python:latest"
  DS_NAME:
    description: "Name of the repo."
    required: true
  DS_YAML:
    description: "Location of Actions workflow YAML file to use."
    required: true
  
  DS_JOBS:
    description: "The name(s) of the jobs to use from the YAML file."
    required: true

  DS_MATRIX_EXCLUDE:
    description: "Matrix items to exclude from the jobs."
    required: false
    default: ""

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.ACTION_IMAGE }}
    - ${{ inputs.DS_NAME }}
    - ${{ inputs.DS_YAML }}
    - ${{ inputs.DS_JOBS }}
    - ${{ inputs.DS_MATRIX_EXCLUDE }}