version: "3"
services:
  downstream_runner:
    build: .
    environment:
      - DS_NAME
      - DS_YAML
      - DS_JOBS
      - DS_MATRIX_EXCLUDE
    volumes:
      - type: bind
        source: /home/runner/work/pytest/pytest
        target: /pytest
        volume:
          nocopy: true
    depends_on:
      - TEST_DB_HOST
  TEST_DB_HOST:
    image: "postgres:latest"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=$USER
      - POSTGRES_DB=pytest_django_should_never_get_accessed
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - ./data/db:/var/lib/postgresql/data
    profiles:
      - postgres
