version: "3"
services:
  downstream_runner:
    build: .
    environment:
      - DS_NAME
      - DS_YAML
      - DS_JOBS
      - DS_MATRIX_EXCLUDE
    volumes:
      - type: bind
        source: /home/runner/work/pytest/pytest
        target: /pytest
        volume:
          nocopy: true
    depends_on:
      - db
  db:
    image: "postgres:latest"
    expose:
      - "5342"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=${USER}
