name: downstream_testing

on:
  push:
    branches:
      - downstream_testing

jobs:
  downstream-ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "pytest-html"
            repo: "pytest-dev/pytest-html"
            jobs: "build_python"
            workflow_name: "actions.yml"
            matrix_exclude: ""
          - name: "pytest-django[postgres]"
            repo: "pytest-dev/pytest-django"
            jobs: "test"
            workflow_name: "main.yml"
            matrix_exclude: |
              checkqa,docs py37-dj30-mysql_innodb-coverage py36-dj22-sqlite-xdist-coverage
              py37-dj22-sqlite-xdist-coverage py38-dj30-sqlite-xdist-coverage 
              py38-dj31-sqlite-xdist-coverage py38-dj32-sqlite-xdist-coverage py39-djmain-sqlite-coverage
              py35-dj22-sqlite_file-coverage py36-dj31-mysql_myisam-coverage py36-dj32-mysql_myisam-coverage

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Checkout ${{ matrix.name }}
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: ${{ matrix.repo }}
        path: ${{ matrix.name }}
    - name: Run Docker - Downstream Runner
      uses: ./testing/downstream_testing
      with:
        DS_NAME: ${{ matrix.name }}
        DS_YAML: ./${{ matrix.name }}/.github/workflows/${{ matrix.workflow_name }}
        DS_JOBS: ${{ matrix.jobs }}
        DS_MATRIX_EXCLUDE: ${{ matrix.matrix_exclude }}
