name: downstream_testing

on:
  push:
    branches:
      - downstream_testing

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "pytest-html"
            python: "3.9"
            os: ubuntu-latest
            repo: "pytest-dev/pytest-html"
            jobs: "build_python"
            workflow_name: "actions.yml"
          #- name: "pytest-django"
          #  python: "3.9"
          #  os: ubuntu-latest
          #  repo: "pytest-dev/pytest-django"
          #  jobs: "test"
          #  workflow_name: "main.yml"

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Checkout ${{ matrix.name }}
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: ${{ matrix.repo }}
        path: ${{ matrix.name }}
    - name: Run Docker - Downstream Runner
      uses: ./testing/downstream_testing
      with:
        DS_YAML: ./${{ matrix.name }}/.github/workflows/${{ matrix.workflow_name }}
        DS_JOBS: ${{ matrix.jobs }}
