name: downstream_testing

on:
  push:
    branches:
      - downstream_testing

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        name: [
          "pytest-html",
          "pytest-django"
        ]

        include:
          - name: "pytest-html"
            python: "3.9"
            os: ubuntu-latest
            repo: "pytest-dev/pytest-html@master"
            tox_env: "-e devel"
          - name: "pytest-django"
            python: "3.9"
            os: ubuntu-latest
            repo: "pytest-dev/pytest-django@master"
            tox_env: ""

    steps:
    - name: Run Target's Action
      uses: ${{ matrix.repo }}
    #- uses: actions/checkout@v2
    #  with:
    #    fetch-depth: 0
    #- name: Set up Python ${{ matrix.python }}
    #  uses: actions/setup-python@v2
    #  with:
    #    python-version: ${{ matrix.python }}
    #- name: Install dependencies
    #  run: |
    #    python -m pip install --upgrade pip
    #    pip install tox coverage
    #- name: Checkout ${{ matrix.name }}
    #  uses: actions/checkout@v2
    #  with:
    #    fetch-depth: 0
    #    repository: ${{ matrix.repo }}
    #    path: ${{ matrix.name }}
    #- name: where are the tox.ini's?
    #  run: |
    #    find -name tox.ini -ls
    # name: Run ${{ matrix.name }} tox
    #  run: |
    #    tox -c $GITHUB_WORKSPACE/${{ matrix.name }}/tox.ini ${{ matrix.tox_env }}
