name: downstream_compose

on:
  push:
    branches:
      - downstream_compose

jobs:
  downstream-ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "pytest-html"
            repo: "pytest-dev/pytest-html"
            docker_profile: "nodb"
            jobs: "build_python"
            workflow_name: "actions.yml"
            matrix_exclude: ""
          
          - name: "pytest-django"
            repo: "pytest-dev/pytest-django"
            docker_profile: "postgres"
            jobs: "test"
            workflow_name: "main.yml"
            matrix_exclude: |
              checkqa,docs py37-dj30-mysql_innodb-coverage py36-dj22-sqlite-xdist-coverage
              py37-dj22-sqlite-xdist-coverage py38-dj30-sqlite-xdist-coverage 
              py38-dj31-sqlite-xdist-coverage py38-dj32-sqlite-xdist-coverage py39-djmain-sqlite-coverage
              py35-dj22-sqlite_file-coverage py36-dj31-mysql_myisam-coverage py36-dj32-mysql_myisam-coverage
          - name: "pytest-django"
            repo: "pytest-dev/pytest-django"
            docker_profile: "mysql"
            jobs: "test"
            workflow_name: "main.yml"
            matrix_exclude: |
              checkqa,docs py36-dj22-sqlite-xdist-coverage py35-dj22-postgres-pytest54-coverage
              py37-dj22-sqlite-xdist-coverage py38-dj30-sqlite-xdist-coverage pypy3-dj22-postgres
              py38-dj31-sqlite-xdist-coverage py38-dj32-sqlite-xdist-coverage py39-djmain-sqlite-coverage
              py35-dj22-sqlite_file-coverage py39-dj31-postgres-xdist-coverage py39-dj32-postgres-xdist-coverage
          - name: "pytest-django"
            repo: "pytest-dev/pytest-django"
            docker_profile: "nodb"
            jobs: "test"
            workflow_name: "main.yml"
            matrix_exclude: |
              checkqa,docs py35-dj22-postgres-pytest54-coverage pypy3-dj22-postgres
              py39-dj31-postgres-xdist-coverage py39-dj32-postgres-xdist-coverage py37-dj30-mysql_innodb-coverage
              py36-dj31-mysql_myisam-coverage py36-dj32-mysql_myisam-coverage

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Checkout ${{ matrix.name }}
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: ${{ matrix.repo }}
        path: ${{ matrix.name }}
    - name: Run Downstream Tests
      run: docker-compose -f ./testing/downstream_testing/docker-compose.yml --profile ${{ matrix.docker_profile }} up --exit-code-from base_${{ matrix.docker_profile }}
      env:
        DS_NAME: ${{ matrix.name }}
        DS_YAML: ./${{ matrix.name }}/.github/workflows/${{ matrix.workflow_name }}
        DS_JOBS: ${{ matrix.jobs }}
        DS_MATRIX_EXCLUDE: ${{ matrix.matrix_exclude }}
        DOCKER_BUILDKIT: 1
