name: downstream_testing

on:
  push:
    branches:
      - downstream_testing

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "pytest-html"
            python: "3.9"
            os: ubuntu-latest
            repo: "pytest-dev/pytest-html"
            jobs: "build_python"
            workflow_name: "actions.yml"
          - name: "pytest-django"
            python: "3.9"
            os: ubuntu-latest
            repo: "pytest-dev/pytest-django"
            jobs: "test"
            workflow_name: "main.yml"

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
    - name: Checkout ${{ matrix.name }}
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: ${{ matrix.repo }}
        path: ${{ matrix.name }}
    - name: find me some yamls
      run: |
        pwd
        find -name ${{ matrix.workflow_name }}
    - name: Run Downstream Runner
      run: |
        python -m testing.downstream_testing.downstream_runner $DS_YAML $DS_JOBS
      env:
        DS_YAML: ${{ github.workspace }}/${{ matrix.name }}/.github/workflows/${{ matrix.workflow_name }}
        DS_JOBS: ${{ matrix.jobs }}
    - name: Run Downstream Runner Docker
      uses: testing/downstream_testing
      with:
        DS_YAML: ${{ github.workspace }}/${{ matrix.name }}/.github/workflows/${{ matrix.workflow_name }}
        DS_JOBS: ${{ matrix.jobs }}
